language: python
sudo: false
python:
  - "3.6"
  
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install pytest
  - travis_wait travis_retry pip install pydot
  - travis_wait travis_retry pip install psutil
  - travis_wait travis_retry pip install dandelion
  - travis_wait travis_retry pip install git+https://github.com/Theano/Theano.git#egg=Theano
  - travis_wait travis_retry pip install torch==1.3.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - travis_retry python setup.py install
script: pytest test

cache:
  - directories:
    - $HOME/.theano
